version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
#   build: .
    image: paragdocker/kafka_jmx
    links:
     - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_OPTS: -javaagent:/usr/app/jmx_prometheus_javaagent.jar=7071:/usr/app/prom-jmx-agent-config.yml
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  prometheus:
    image: paragdocker/prometheus
    ports:
      - 9090:9090/tcp
#    volumes:
#      - ./mount/prometheus:/etc/prometheus
    links:
      - kafka
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000/tcp
    links:
      - prometheus